Fixing issue #38 AttributeError 'NoneType' object has no attribute 'json_string' (#41)
* Bump to Quill Version 1.3.7

Bump to Quill Version 1.3.7 - This version of Quill fixes Quill Vuln https://github.com/quilljs/quill/issues/2438

Here is the change commit to fix the vuln in Quill https://github.com/quilljs/quill/pull/2439

The Vuln is described here: https://ossindex.sonatype.org/vuln/d96c07dd-81f9-41f6-b2bd-531143bcaeab

* Adding JS/CSS include instructions from README.md

Resolves issue [#33](https://github.com/LeeHanYeong/django-quill-editor/issues/33)

* adding None return for json_string